project:
  type: website
  output-dir: _site

website:
  title: "Cham QMagSpin Lab"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: news.qmd
        text: News
      - href: join.qmd
        text: Join Us
    right:
      - icon: envelope
        href: mailto:YOUR_EMAIL@ntu.edu.sg
        aria-label: Email
  page-footer:
    left: |
      **Cham QMagSpin Lab**  
      Quantum Magnonics & Spintronics
    right: |
      School of Electrical and Electronic Engineering  
      Nanyang Technological University, Singapore
  search: false

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    anchor-sections: false

execute:
  freeze: auto
