project:
  type: website
  output-dir: _site
  resources:
    - assets/**

website:
  title: "Cham QMagSpin Lab @ NTU EEE"
  site-url: "https://chamgroupntu.github.io/qmagspin-lab/"

  navbar:
    pinned: true
    logo: "assets/logo.svg"
    logo-alt: "Nanyang Technological University"

    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: news.qmd
        text: News
      - href: join.qmd
        text: Join Us

    right:
      - icon: envelope
        href: mailto:jerald.chamtm@ntu.edu.sg
        aria-label: Email

  page-footer:
    left: |
      **Cham QMagSpin Lab**  
      Quantum Magnonics & Spintronics

    right: |
      School of Electrical and Electronic Engineering  
      Nanyang Technological University, Singapore

  search: false


format:
  html:
    theme:
      - cosmo
      - styles.scss

    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    anchor-sections: false


execute:
  freeze: auto