---
page-layout: article
---

::: {.join-page}

::: {.page-hero}
<div class="section-kicker">Join Us</div>

# Join the group

We are building a new research group at NTU EEE working at the intersection of quantum materials, ultrafast spectroscopy, terahertz science, magnonics, and spintronics.
:::


## PhD students

We welcome enquiries from prospective PhD students interested in experimental condensed matter physics, quantum materials, magnetism, spintronics, ultrafast spectroscopy, and terahertz science.

**We have openings for the Jan 2027 and Aug 2027 intakes**. Ph.D. positions are fully funded and supported by [NTU Research Scholarships](https://www.ntu.edu.sg/admissions/graduate/financialmatters/scholarships). Graduating students considering graduate studies are encouraged to get in touch to learn more and will be guided through the applications process.


## Postdoctoral researchers

We welcome prospective postdocs interested in research at the intersection of ultrafast spectroscopy, terahertz science, spintronics, and low-dimensional quantum materials.

**Postdoctoral fellowship opportunities are available.** See [NTU Research Careers](https://www.ntu.edu.sg/research/research-careers) for current fellowship and research opportunities.

Interested candidates are encouraged to contact us to discuss research interests, potential projects, and suitable fellowship opportunities.


## Undergraduate researchers

We welcome motivated NTU undergraduate students interested in gaining research experience in quantum materials, optics, magnetism, spintronics, and related experimental techniques.

ultrafast and terahertz spectroscopy, nanoscale device fabrication, electrical and optical measurements of spin dynamics, and the development of new spectroscopic techniques for probing quantum phenomena in 2D heterostructures.


## Get in touch

If you are interested in joining the group, please email [Prof. Cham](mailto:jerald.chamtm@ntu.edu.sg) to find out more about scholarship and fellowship opportunities.

:::